name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, '[0-9]+-[0-9]+-*']
  workflow_dispatch:
  workflow_run:
    workflows: ['Dependabot']
    types:
      - completed
  workflow_call:

jobs:
  test:
    name: Test
    if: ${{ !startsWith(github.head_ref, 'workflows/tests/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event_name != 'workflow_run' }}

      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'workflow_run' }}
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Test
        uses: ./
        with:
          timeout: 600
          fail-if-timeout: true
