name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, '[0-9]+-[0-9]+-*']
  workflow_dispatch:
  workflow_run:
    workflows: ['Dependabot']
    types:
      - completed
  workflow_call:
    inputs:
      ref:
        description: 'Checkout a different git ref instead of the SHA from the GitHub event.'
        required: false
        type: string
jobs:
  test:
    name: Test
    if: ${{ !startsWith(github.head_ref, 'workflows/tests/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Test
        uses: ./
        with:
          timeout: 600
          fail-if-timeout: true
